### ISSUE TITLE
Pandapower conversions

### ISSUE THREAD

**Issue by nitbharambe** [PowerGridModel/power-grid-model-io#1]
The central task is to `power-grid-model`  or pgm to `pandapower` or pp so it can be used as a simple argument in `pp.runpp` to run powerflow calculation on pandapower `net` data using power-grid-model.

On pandapower side, this would be accomplished by pandapower importing `power-grid-model-io` and `power-grid-model`. 
- First convert from pp net to pgm numpy structured array input data
- Running calculations: `calculate_power_flow` or `calculate_state_estimation`
- Convert numpy structured array results to pp net dataframes

## Roadmap for creating conversions

Conversion is to be implemented in this repository. Following steps to be followed

- Basic conversions
  - Simple mapping elements in yaml config: Node, line, sym/asym loads/gen, shunt
  - Conversion rules or filters (unit changing, str to other str or enum, etc)
  - Node/bus id bookkeeping required. 
- `read_pp_net` function and maybe pp_converter.py, discuss later.
- Grid attributes conversion: freq, calculation method, iterations, initialization etc
- Switches and bookkeeping of switches
- Complex component mapping: source, trafo, 3wdg trafo, vtg and power sensors.

Unit tests and example: 
- Any tests related to the code (bookkeeping, filters etc)
- Sample grid

## Input Data validation

- All unsupported work

## Not planned yet

Complex or unimplemented features not planned yet

- Input Validation: pp or pgm?
- Batch calculation
- Result conversion
- pp side of code (Discuss with pp people, maybe conversion will have pp net as input and res_*  dataframes as output.)

# Task on pandapower repository

After the conversion is done. The pandapower repository can be modified with additional core from power grid model.
https://github.com/e2nIEE/pandapower/issues/1591

**Comment by TonyXiang8787** [comment]
We are not going to implement batch conversions in short term.
