### ISSUE TITLE
[BUG] PgmJsonConverter may write floats as integers

### ISSUE THREAD

**Issue by mgovers** [PowerGridModel/power-grid-model-io#203]
**Describe the bug**

If a floating point has no (decimal) fraction (e.g. `310.0`), then it is serialized as an integral (e.g. `310`) instead of a floating point (e.g. `310.0`)

**Expected behavior**

floating points are always serialized as floating points with fractions (e.g. `310.0`)

**Screenshots**

**Additional context**

**Comment by TonyXiang8787** [comment]
Why is this a bug? `json` specification mandates that there is no distinction between number with or without decimal. `json` only knows the number data type, not integer or float.

**Comment by TonyXiang8787** [comment]
https://json-schema.org/understanding-json-schema/reference/numeric

**Comment by mgovers** [comment]
from the schema, the current behaviour is indeed cfr spec and therefore correct. AFAIAC we can close this. c.c. @SteffanWullems

**Comment by mgovers** [comment]
sooo... can we close this ticket then as a won't fix?

**Comment by mgovers** [comment]
I will close this issue now, because:

* no additional input was provided
* the JSON standard does not officially support the distinction between `Float` and `Integer` (both are considered `Number`s)
* the current implementation uses a 3rd party package for the actual serialization, which in turn serializes in a format officially supported by JSON, and the added value seems lower than the implementation effort to write our own JSON serializer

We can always reopen if necessary.
