### ISSUE TITLE
[FEATURE] Support for multiple Vision Excel versions 

### ISSUE THREAD

**Issue by Jerry-Jinfeng-Guo** [PowerGridModel/power-grid-model-io#225]
Vision 9.7 has introduced many changes to the exported excel sheet, which brings challenge to the existing `VisionExcelConverter`. Most significantly, UUID was introduced as the new id scheme. However, older versions like <9.6 are still extensively used by users who wish to take advantage of PGM as their compute core. To address this, we need to update our code base to accomdate the changes.

Here is the proposed temporary work-around:
 - Process the new excel sheets in a separate routine and make it backwards compatible\
 - - The argument is simple: this approach requires minimum changes to the code base and PGM internally do not depend on UUID's, and there is hardly any benefits in its current applications.

In the case that `VisionExcelConverter` is to be continued, here are the proposed solutions:
- Open `*.yaml` configuration files as parameters to the converter. Currently one file is provided and users need to modify that versioned file or they need to go deep to the converter definition code to load any other configuration file. By making this a parameter, we could explicitly offload the whole `*.yaml` configuration task to users.
- Treat old `Number`/`Node.Number` the same as `GUID`/`Node.GUID` and convert them all to strings in python. They are then collected to a map where each string key maps to an integer. This way, we combines the existing id scheme well with both Vision 9.7 UUID based scheme and Vision sub 9.6 number based scheme.
- Extra care is needed trying to map terms: for instance, Vision 9.7 refer to `N1` now as `Grounding1`. Many other such changes need to be mapped out accurately.

**Comment by mgovers** [comment]
Regardless of the path going forward, exposing the `*.yaml` configuration file is a good idea. Hasn't this been done already?

**Comment by Jerry-Jinfeng-Guo** [comment]
Nope, not yet. Hence that will be the first PR in this issue.

**Comment by mgovers** [comment]
> Nope, not yet. Hence that will be the first PR in this issue.

can you do that when you have time? i think this is important and small enough to "just do it"

**Comment by Jerry-Jinfeng-Guo** [comment]
Step 1: https://github.com/PowerGridModel/power-grid-model-io/pull/226 @mgovers If you could give a review

**Comment by Jerry-Jinfeng-Guo** [comment]
Step 0: https://github.com/PowerGridModel/power-grid-model-io/pull/227

**Comment by Jerry-Jinfeng-Guo** [comment]
Step 1-3: https://github.com/PowerGridModel/power-grid-model-io/pull/232

**Comment by mgovers** [comment]
@Jerry-Jinfeng-Guo , #232 is merged. This issue can be closed, right?

**Comment by Jerry-Jinfeng-Guo** [comment]
> @Jerry-Jinfeng-Guo , #232 is merged. This issue can be closed, right?

Yes.
