### ISSUE TITLE
[FEATURE] Add documentation about GUID handling

### ISSUE THREAD

**Issue by petersalemink95** [PowerGridModel/power-grid-model-io#247]
Vision 9.7 provides GUID instead of Number/Subnumber as identification of objects. This new format is handled internally now, but there is now documentation about it.

We need to add doumentation on how it works and also how the old yaml file can should still be used (new users might not know about Number/Subnumber at all

**Comment by Jerry-Jinfeng-Guo** [comment]
Documentation is added following https://github.com/PowerGridModel/power-grid-model-io/pull/249
